/**
 * inputInvalidException involves all the Exceptions generated by violating some rules:
 * if a filed with a incorrect format
 * If a filed with invalid data according to system rules((no duplicate account numbers are allowed,
 * savings accounts cannot have negative balances.....saving accounts start with 8, chequing accounts 7)
 * if happens, it will throw this inputInvalidException
 * @author Yuhang Zhao, student number: 150467199
 *
 */
public class inputInvalidException extends Exception {
	public inputInvalidException() {
		super();
	}
	public inputInvalidException(String msg) {
		super(msg);
	}
}
